### ISSUE TITLE
Opacity sliders aren't working

### ISSUE THREAD

**Issue by rbrtmrtn** [CityOfPhiladelphia/mapboard#45]
When you click the Zoning tab the slider appears in the wrong location and isn't operable

**Comment by ajrothwell** [comment]
This is because the BASE_CONFIG_URL is set to //rawgit.com/rbrtmrtn/mapboard-base-config/2fbe59eb4bc61b782c5e3723e764945f7fffed85/config.js which does not have opacity values for dynamicMapLayers.

I had been using //raw.githubusercontent.com/rbrtmrtn/mapboard-base-config/develop/config.js which does have those values
